import LoginPageContainer from './LoginComponent';
import Dashboard from './Dashboard';
import CreateNotificationFlow from './CreateNotificationFlow';
import EditTemplateConatiner from './EditTemplate';
import RecepientDetails from './RecepientDetails';
import YourNotificationContainer from './YourNotifications';
import RegestrationPageContainer from './Regestration';
export default LoginPageContainer;
export { Dashboard };
export { CreateNotificationFlow };
export { EditTemplateConatiner };
export { RecepientDetails };
export { YourNotificationContainer };
export { RegestrationPageContainer };